include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
    - '**/*.g.dart'
    - '**/*.freezed.dart'
  errors:
    invalid_annotation_target: ignore
    removed_lint: ignore

linter:
  rules:
    # Style
    prefer_single_quotes: true
    always_declare_return_types: true
    avoid_print: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_final_fields: true
    prefer_final_locals: true
    unnecessary_this: true
    use_super_parameters: true

    # Safety
    avoid_dynamic_calls: true
    cancel_subscriptions: true
    close_sinks: true
    unawaited_futures: true
