<?php

namespace App\Http\Middleware;

use Closure;
use Illuminate\Http\Request;
use Illuminate\Support\Str;
use Symfony\Component\HttpFoundation\Response;

/**
 * AddRequestIdMiddleware
 *
 * Ensures every HTTP response carries an `X-Request-ID` header.
 *
 * Behaviour:
 *  1. If the incoming request already contains an `X-Request-ID` header, that
 *     value is echoed back unchanged (client-supplied tracing ID).
 *  2. Otherwise a new UUID v4 is generated and used.
 *  3. The resolved request ID is stored in the request bag as `_request_id` so
 *     that controllers and services can read it via
 *     `$request->attributes->get('_request_id')` or
 *     `$request->header('X-Request-ID')` (the header will already be present).
 *  4. The header is set on the outgoing response regardless of HTTP status code,
 *     including error responses generated by exception handlers.
 *
 * Requirements: 18.10
 */
class AddRequestIdMiddleware
{
    /**
     * Handle an incoming request.
     */
    public function handle(Request $request, Closure $next): Response
    {
        // Resolve or generate the request ID
        $requestId = $request->header('X-Request-ID');

        if (! $requestId || ! Str::isUuid($requestId)) {
            $requestId = (string) Str::uuid();
        }

        // Inject the resolved ID into the request so downstream code can use it
        // without re-reading the header.
        $request->headers->set('X-Request-ID', $requestId);
        $request->attributes->set('_request_id', $requestId);

        /** @var Response $response */
        $response = $next($request);

        // Attach to the outgoing response
        $response->headers->set('X-Request-ID', $requestId);

        return $response;
    }
}
